### ISSUE TITLE
add arguments parsing

### ISSUE THREAD

**Issue by Frederick67** [gekigek99/minecraft-server-hibernation#103]
I use this program in pterodactyl panel but it isn't possibible to change the config after install. Can you add an startup argoment for set server ram?

**Comment by gekigek99** [comment]
yea sure it might be useful!

@BolverBlitz also suggested these parameters to be used as arguments:
```
HibernationInfo
StartingInfo
FileName
Protocol
Version
Debug
Xms128M
Xmx2048M
```

**Comment by gekigek99** [comment]
added in 0539640054ca4776c05ff3ada9c0b1b5bff3ea55
