### ISSUE TITLE
What version do I put for Fabric?

### ISSUE THREAD

**Issue by kowasaur** [gekigek99/minecraft-server-hibernation#115]
My server is running the latest version of Fabric for 1.17.1. I've tried `1.17.1`, `fabric`, `1.17.1/fabric` and `fabric-loader-0.11.6-1.17.1` for the version in the config.json but I'm still not able to join the server. I've also tried just removing the version and I can't join either. Btw I am on an M1 Mac

**Comment by gekigek99** [comment]
The `version` and `protocol` are not important for the connection, they are used only as an info for the clients.

The problem might be in a problem in the setup/config.

Can you send the full config file?

Can you specify the setup? What are you using as a server? Is the server on LAN?

After setting the debug to `true`, launch msh and execute the command `msh start`: is some error reported?

**Comment by gekigek99** [comment]
closed for inactivity
