### ISSUE TITLE
Console shuts down without any feedback

### ISSUE THREAD

**Issue by Nester23** [gekigek99/minecraft-server-hibernation#117]
### I'm setting up this script for the first time, but it keeps shutting down without leaving a single clue why.
_So here's what happens:_
![helpnowork](https://user-images.githubusercontent.com/66305483/129332774-c6b3796f-3835-44de-b4c7-303c0c161d52.gif)
**Here's an archive with most of the files:** _(paper server core didn't fit)_
[hiber-serv.zip](https://github.com/gekigek99/minecraft-server-hibernation/files/6981279/hiber-serv.zip)

**Comment by gekigek99** [comment]
ok for what i can see it seems to be configured correctly...

can you launch a `cmd terminal` and execute `msh-v2.4.0-windows-x86.exe` from there?  
_It should give you the possibility to observe the error, please report the log here_

**Comment by Nester23** [comment]
> _It should give you the possibility to observe the error, please report the log here_

`main: loadConfig: open config.json: The system cannot find the file specified.
`

**Comment by gekigek99** [comment]
it's a problem of from where the command is executed (nothing to do with the script), try this:

`cd "D:\Nester\Random\Minecraft servers\Versions\1.17.1\hiber-serv\" && msh-v2.4.0-windows-x86.exe`

I'll check if I can do anything within the code

**Comment by Nester23** [comment]
It says that **msh-v2.4.0-windows-x86.exe** isn't an internal or external command or an executable...

**Comment by Nester23** [comment]
Wait, I got it to work with a .bat!

**main: loadConfig: setIpPorts: TargetPort and ListenPort appear to be the same, please change one of them**

**Comment by gekigek99** [comment]
> main: loadConfig: setIpPorts: TargetPort and ListenPort appear to be the same, please change one of them

the **port parameter** in `server.properties` and in `config.json` must be different values _(please remember to connect to the server using the port specified in `config.json`)_

**Comment by Nester23** [comment]
ty, I see what I did wrong now
![изображение](https://user-images.githubusercontent.com/66305483/129461439-f085ccba-9b1f-4234-84b5-ef8aba1dcc32.png)
_So, when configuring it, I read the word "**port**", then took a quick glance at the number there, seen `255xx` and assumed that it was `25565` in there._
### I didn't notice that there was supposed to be a different port for the script itself.


---
**Anyways, thank you for your help! Have a good day!**

**Comment by gekigek99** [comment]
ah good to know you solved it! have fun!

if you like msh please give a star to the repository!

**Comment by Nester23** [comment]
> if you like msh please give a star to the repository!

![изображение](https://user-images.githubusercontent.com/66305483/129471716-44eaded1-5780-4443-913f-ba6292011f8e.png)
_Nice_
