### ISSUE TITLE
High CPU utilization on idle

### ISSUE THREAD

**Issue by cromefire** [gekigek99/minecraft-server-hibernation#121]
I've noticed some high CPU utilization in idle, when the server is in hibernate. According to `htop` msh seems to be hammering one thread/core constantly. I'm using `v2.4.4`. It seems to increase the following areas: system (probably via syscalls), IRQs and userspace.

**Comment by gekigek99** [comment]
Thanks for reporting.

Can you specify the OS and hardware that you are using?

What is the usage percentage?

Can you tell me that steps to reproduce this behaviour?

**Comment by cromefire** [comment]
OS is Ubuntu 20.04 on an i5-6600. Usage percentage is slightly under 25% basically smashing a single thread by a 100%.
In my case I can just reproduce it by simply running it and I'll have to confirm again (I'm pretty sure, but not 100% sure) if it's right off the start or if it's after the first hibernation that the issue arises.

**Comment by gekigek99** [comment]
> if it's right off the start or if it's after the first hibernation that the issue arises.

Can you check which is the case?

> it looks to me like some infinite loop that is missing a sleep call or something like that.

There was a bug a few months ago similar to this but msh would just crash after 1 minute.

Can you compile the the rep at the latest commit on the dev branch? (Just to make sure we are analyzing the lastest change)

**Comment by cromefire** [comment]
> Can you try adding `runtime.GOMAXPROCS(runtime.NumCPU())` in the "main" function before anything else? Then tell me what happens.

No change

> Can you check which is the case?

It seems to be the case all the time, while running, right after the start and while hibernating.

> Can you compile the the rep at the latest commit on the dev branch? (Just to make sure we are analyzing the lastest change)

No change either.

**Comment by gekigek99** [comment]
on windows it does not seem to happen (CPU is <0.01%)

![image](https://user-images.githubusercontent.com/53654579/141201522-55590aa3-3875-4b94-833d-423a7f3cea44.png)

tomorrow I'll check on linux

**Comment by gekigek99** [comment]
what golang version are you using to compile msh? are you using additional parameters for compilation?

**Comment by cromefire** [comment]
> what golang version are you using to compile msh? are you using additional parameters for compilation?

No special parameters, just `go build`, built it with version 1.17.

**Comment by gekigek99** [comment]
Ok I'll test it with that version.

In the meantime try compiling it with version 1.15

**Comment by gekigek99** [comment]
also on my linux VM there is no problem

![image](https://user-images.githubusercontent.com/53654579/141379752-2a8186c0-ce5c-4bb6-bc31-e13ced903680.png)

in both tests (linux and windows) I was using golang version `1.15.10`. Would you mind trying compiling msh with this version and check if the problem persists?

**Comment by gekigek99** [comment]
UPDATE:
![image](https://user-images.githubusercontent.com/53654579/141382711-644b3bd4-e53b-4325-a495-172d20b12613.png)

this test was done on linux with golang version `1.17.3` and the problem does not seem to exist

**Comment by cromefire** [comment]
Will test 1.15, any way I can generate a profile of the executable? I still have one idea: It's running in a systemd jail, so highly restricted in it's use of certain syscalls and filesystem usage so maybe it's running against a wall there I'll also test it without the hail and see it it's triggering the same behavior.

**Comment by gekigek99** [comment]
I am using it also on some Linux servers and no problem there either.

Ok tell me what happens with 1.15 but I guess it won't change anything

What do you mean by generating a profile of the executable? (You are free to do investigate as mush as you want ;) )

What do you mean by "hardening"?

Maybe your configuration of the system process has something strange in it. Msh does really few syscalls (especially when the Minecraft server is not running) and even the few that are done are very basic and common ones (like print to terminal aahahah)

Have you tested on an other machine? On windows you can use processmonitor or processexplorer which can analyze processes pretty deep down.

**Comment by cromefire** [comment]
> What do you mean by generating a profile of the executable? (You are free to do investigate as mush as you want ;) )

I meant runtime [profiling](https://en.wikipedia.org/wiki/Profiling_%28computer_programming%29) that can be used to see, which functions take most of the time.

> What do you mean by "hardening"?

> Maybe your configuration of the system process has something strange in it. Msh does really few syscalls (especially when the Minecraft server is not running) and even the few that are done are very basic and common ones (like print to terminal aahahah)

Just standard hardening that should be applied to all internet accessible services: Restricting access to cgroups (only used in containerization), restricting use of setuid/setgid (prevent privilege escalation), private tmp, devices and filesystem protection (the server and msh don't need to read and write in other program's files). I've used it with most services until now (the server it self also doesn't have a problem) and the only issues it might cause is crashing if the program tries to call a syscalls that's not allowed, but all of them are Linux specific.

> Have you tested on an other machine? On windows you can use processmonitor or processexplorer which can analyze processes pretty deep down.

I guess I can try.

**Comment by gekigek99** [comment]
> I meant runtime profiling that can be used to see, which functions take most of the time.

A Okok sure can you analyze that on your machine? I can do it on mine and then we compare results

> the only issues it might cause is crashing if the program tries to call a syscalls that's not allowed, but all of them are Linux specific.

But msh is not crashing no? 

Anyway it might be due to this kind of hardening you are using on the machine... Still I'm interested in knowing more about it since soon enough I'll start to play with Minecraft server process suspend/unsuspend and that's a little more tricky.

Next step is to do some profiling of the msh executable runtime.

**Comment by cromefire** [comment]
> But msh is not crashing no?

No that's the thing, it just blocks some stuff, so it should either be fine or crash, I've never seen degraded performance. And I mean every thing does work and it doesn't seem to be unresponsive.

Will investigate tomorrow. I've found pprof, which I can import and visualize in goland.

**Comment by cromefire** [comment]
![image](https://user-images.githubusercontent.com/26320625/141649996-47f672ef-8358-4039-b8fb-ebd400396aaa.png)
I think I found the culprit. You try to read the input and retry on failure:
![image](https://user-images.githubusercontent.com/26320625/141650042-4cd496c3-a50c-4c27-b824-1e7c1a63219f.png)
Systemd (running it as a daemon) isn't providing it with any input and so it always fails. I have a fix that seems to be working fine, I'll create a PR.

**Comment by gekigek99** [comment]
thanks a lot for investigating and writing the solution for the issue, I'll soon accept the PR.
In the meantime, if you like msh, please give it a star on github.
