### ISSUE TITLE
server icon and frozen icon not working

### ISSUE THREAD

**Issue by CheeseBender** [gekigek99/minecraft-server-hibernation#125]
So the title says it. I have both 64x64 images in png format in my server folder, and I also tried in the user folder and in the msh folder, but the systems doesn't seem to be able to find them. The image displayed is just a minecraft sun with black background.

**Comment by gekigek99** [comment]
What version are you using?

The image must be in the server folder and be named `server-icon-frozen.png`

**Comment by CheeseBender** [comment]
Yeah I actually solved it, but I'm not entirely sure how. If I start the script (./msh) from a different directory it's not going to work properly, so I have to do cd /script/directory and then execute it.

**Comment by CheeseBender** [comment]
Not necessarily an issue, but would have thanked knowing that in advance.

**Comment by gekigek99** [comment]
Maybe try putting the absolute path (and not `./path/to/server`) in the msh config
