### ISSUE TITLE
CPU usage really high

### ISSUE THREAD

**Issue by CheeseBender** [gekigek99/minecraft-server-hibernation#126]
![image](https://user-images.githubusercontent.com/95391035/145729455-52a7fed9-e615-4c9a-a539-e5e737691978.png)
This is a really counterproductive thing to have on a program meant to reduce mean cpu usage. This happens even when my server is stopped.

**Comment by gekigek99** [comment]
Ahahahah yep, there is definetly some problem...

What version are you using?
Os?
What is your setup and config?

**Comment by CheeseBender** [comment]
Mc version 1.18, msh version 2.4.0, os gnu linux.
Not sure what do you mean with setup, but I had a cronjob to execute the script on boot, which was potentially the issue, because if I execute it manually then there's no cpu overload.

This is my config
```
{
  "Server":{
    "Folder": "/home/opc/CNBAProject",
    "FileName": "cnbaproject.jar",
    "Version": "1.18",
    "Protocol": "754"
  },
  "Commands":{
    "StartServer": "java -Xms8G -Xmx8G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch -Dlog4j2.formatMsgNoLookups=true -jar cnbaproject.jar nogui",
    "StopServer": "stop",
    "StopServerForce": ""
  },
  "Msh":{
    "Port": "25555",
    "HibernationInfo": "                   \u0026fEstado del Servidor:\n          \u0026b\u0026lApagado. Metete para abrirlo.",
    "StartingInfo": "                     \u0026fEstado del Servidor:\n                     \u00266\u0026lIniciándose...",
    "TimeBeforeStoppingEmptyServer": 60,
    "CheckForUpdates": false,
    "Debug": false
  }
}
```

**Comment by gekigek99** [comment]
It's probably a known bug, check it here: https://github.com/gekigek99/minecraft-server-hibernation/issues/121

To solve it you need to compile msh from the dev branch.

If you have problems with that tell me

**Comment by gekigek99** [comment]
@CheeseBender did you solve the problem?

**Comment by CheeseBender** [comment]
Yes! Sorry for being late. Yes, the dev branch completely patches this issue and I now can run msh with a cronjob without a cpu overload. Thank you!

**Comment by gekigek99** [comment]
glad to hear that @CheeseBender! if you like this project please consider leaving it a star!
