### ISSUE TITLE
Python Docker: not functional

### ISSUE THREAD

**Issue by lubocode** [gekigek99/minecraft-server-hibernation#17]
The python Dockerfile and script on Branch "docker" currently do not work.

1. Implement argument parsing into the script
2. Add listening for termination signal from Docker container in script
    -> Add server shutdown upon script exit
3. Relocate python script to inside Docker image during build process of Dockerfile
4. Add ENV variables for argument parsing in Dockerfile
5. Create README for python docker

**Comment by gekigek99** [comment]
@lubocode i added you in the credits, are you still planning on developing the docker version?

**Comment by lubocode** [comment]
Hey @gekigek99 ,
yes I do plan to go over your changes in the near future. I just finished with the exams for this semester and had a quick look at all the work you did in the past weeks.
I still don't exactly know how to do it. I will probably create a pull request from the master to the docker branch and manually resolve it. There is a little bit that's done differently in the docker script and that blocks an automatic merge.
I never merged changes from the master into a sub branch though, so maybe that is not the right way to do it.
All online comments just displayed how to initiate the merge locally over the command line, though resolving issues there might be harder than doing it over the online GUI via a pull request...

If you have experience with that, kindly let me know. Otherwise I will just try it the pull request way.

**Comment by gekigek99** [comment]
I'm not an git expert either... But creating a pull request from the main to the docker seems doable on the online gui...  

(what files need to be different from the main and what are the differences to be made? Maybe we can discuss a way to create a sort of standard layout, so that it will be easyer (if not automatic) the merging process for future upgrades)

**Comment by lubocode** [comment]
The script needs to be able to handle flags in the docker and maybe some other stuff is slightly different.
Also there is the Dockerfile and the README which is meant for Dockerhub.

I can create an overview while doing the pull request and save that as the main (root) README of the Docker branch.

**Comment by lubocode** [comment]
Also, I added a defer for stopping the MC server on script shutdown in the main. (It is currently in a weird place in the socket-for-loop, but will be moved to before the loop)

I would like to add that to the main branch go script as well in the defer func you already created.

**Comment by gekigek99** [comment]
Okok I understand... If there is something (not to radical) I can do in the main branch to make life easyer tell me!

For the defer function it could be useful... It would just be nice to implement that also on the python script to keep them as similar as possible

(If you want you can write the defer function to stop the server and then make a commit request so that you appear as a contributor on the board)

P.s (just to keep you updated) in the next weeks I would like to move the settings in an external json file and implement a function that recognize when the server is online (instead of waiting a fixed amount of time) and set the status as such

**Comment by gekigek99** [comment]
@lubocode when you think the docker version is ready we can do a release!😁

**Comment by lubocode** [comment]
Well, I have been using the current version since half a year^^ It's been working well and I haven't had any problems except for some minor stuttering now and then, though that may be just a Minecraft problem.
I will have to switch some things around on Dockerhub to test the code after the pull request has been resolved and then we can dedicate that as an "official" first release.
Testing on Windows is possible, but I have to figure some stuff out for that and that will take some time.

I will create the pull request today and try to resolve it over the following week. Depending on some things, it might take until the week after, but no longer than that.

**Comment by gekigek99** [comment]
ok that sounds perfect!

Just to specify, the concept of "keeping the py and go version as similar as possible" is valid for the master branch, for the docker you can decide what it's best for you (you can remove the windows compatibility if it's a problem...)

when we'll create a new docker release we'll specify on which version of the master it's based on and what are the differences.

**Comment by gekigek99** [comment]
@lubocode if you find something worth of notice please add it to the wiki... (to keep some sort of documentation to help ourselfs and others in case someone else wants to join)

**Comment by lubocode** [comment]
> I can create an overview while doing the pull request and save that as the main (root) README of the Docker branch.

Opted for noting the differences in the wiki.

Pull-request of latest changes into docker branch is done.
Need to test now and afterwards I can work on the python docker version.

**Comment by gekigek99** [comment]
> Opted for noting the differences in the wiki.

ok it's better in this way

**Comment by lubocode** [comment]
Going to maintain only the GO Docker version
