### ISSUE TITLE
Go Docker: config.json location

### ISSUE THREAD

**Issue by lubocode** [gekigek99/minecraft-server-hibernation#35]
The location of the config.json inside the docker does not make much sense without further info, as it is not easy to change.

I have three ideas for this:
- Copy the config upon docker build into the volume (only possible if docker image is build by oneself and not pulled from Dockerhub, so probably not the best option)
- Have a warning in the Docker readme that the config.json has to be downloaded from the github repo and put beside the minecraft.jar
- Have the config.json inside the container with the script and include instructions in the Docker readme on how to change it with vim or something like that over the linux shell of the container

That being said, it will still work without the user touching the config, but having options is always nice.

**Comment by gekigek99** [comment]
> Have a warning in the Docker readme that the config.json has to be downloaded from the github repo and put beside the minecraft.jar

from the point of view of a general user this is probably the more approachable solution right?
what are the implications of this choice? (like, is the user still able to modify the json without entering the container?)

**Comment by lubocode** [comment]
Yes, the user would be able to modify the config.json without entering the container.
It would need to be pasted besides the server.jar in the volume attached to the docker container.

The process of downloading this could be automated inside the go script, though I do not know how complicated that would end up being. First it should work. Automation can come later. Also issue #31 needs to be resolved first anyway.

**Comment by gekigek99** [comment]
> issue #31 needs to be resolved first anyway.

completely agree

can the go script from inside the container modify files outside?

**Comment by gekigek99** [comment]
> The process of downloading this could be automated inside the go script, though I do not know how complicated that would end up being. First it should work.

as beginning you could just write some instructions in the readme of your branch

**Comment by lubocode** [comment]
> can the go script from inside the container modify files outside?

Yes. The volume is basically just a folder for the things inside the container.

**Comment by gekigek99** [comment]
ok so the I think that for the 2 option there are no cons and is probably the best solution...

**Comment by lubocode** [comment]
@gekigek99 I am currently thinking of using the config.json to only save the server version and protocol and keep everything else modifiable by Docker environment variables. This would remove the need to download the config, as it could be copied inside the image during the Docker build process.
Additionally, I would then add flag parsing for server start and stop times, as well as the debug flag.

**Comment by gekigek99** [comment]
ok i think it's doable.

just keep in mind that for the different enhancement issues we have currently open the parsed string will be quite long
(+ if i manage to solve issue #30 you will need to parse also the image file)

**Comment by lubocode** [comment]
Yeah, well, most of the variables are optional anyways and have a default value assigned, if not specified.

**Comment by gekigek99** [comment]
Ok!
in any case we can adapt it to the different variables once we create those variables

**Comment by lubocode** [comment]
Not yet, I still have to implement it.
Will close it myself, when done.

**Comment by lubocode** [comment]
I figured out the problem with having a different base image for the docker with some help from a friend.

That means I can now focus on catching up with the recent changes and then have a look at implementing some sort of config.json for saving stuff like the server version and protocol.
Most modifiable stuff will stay as docker environment variables/go script flags.

Further progress will be a bit slower though, since uni started again^^

**Comment by gekigek99** [comment]
> the problem with having a different base image for the docker

what kind of problem did you have?

**Comment by lubocode** [comment]
https://github.com/lubocode/minecraft-server-hibernation/issues/4

**Comment by lubocode** [comment]
I will stick to Docker arguments for the configuration of the script.
The config file will be used to keep info about server version and protocol and whatever might come that is auto detected.
The config path will be in the minecraft server path that leads to the Docker volume.
