### ISSUE TITLE
Auto-detect when server is up

### ISSUE THREAD

**Issue by Br31zh** [gekigek99/minecraft-server-hibernation#37]
Hello,

Do you think it’s possible to auto-detect when the server is up instead or using an static defined timer? By trying to connect to it, or using rcon, for example.

**Comment by gekigek99** [comment]
yes it's definitely doable and I have it in my to-do list...

right now we are experiencing some problems (look at the issues ahah) so probably this feature will only be available next month or so...

so i advise you to keep updated with this rep

p.s. if you notice any bug or problem (either with python or go version) please report it ;)

**Comment by Br31zh** [comment]
Yeah, I looked on the issues, I understand that you have more important things to do. But with an issue we can keep tracking the progression and see what is already on the way ^^

Thanks for your answer.

PS : I prefer Python for now, and using this version, via a systemd service. It’s the best tool to do auto start and stop I tried so far, good job ^^

**Comment by gekigek99** [comment]
> But with an issue we can keep tracking the progression and see what is already on the way ^^

yep this is why i'll keep it open with the enancement feature tag

> It’s the best tool to do auto start and stop I tried so far, good job ^^

good to know! thank you! if you like this rep please leave a star, i'll update you when i implement your feature

**Comment by lubocode** [comment]
If one wants to be extra fancy, it might be possible to save the last startup duration in the config for ServerStartupTime.
Depending on the implementation of the server status check of course. If it checks once every second, then this might be doable, if it is much slower, the practical advantages over a manually set time might be marginal.

**Comment by gekigek99** [comment]
Is i though of that too... Sort of tring to predict how much time till the server is up

It could be a quite interesting small feature

**Comment by gekigek99** [comment]
With the addition of minecraft server terminal this should be very easy to implement and much more cleaner than the previous solution...

I will try to make it happen today ;)

**Comment by gekigek99** [comment]
this feature was added in fca264a146efb4e3d773d6a1cfa15b7050f88b7d
