### ISSUE TITLE
Check for server.jar on startup of script

### ISSUE THREAD

**Issue by lubocode** [gekigek99/minecraft-server-hibernation#40]
Checking whether or not the server.jar can be found on script startup should be essential to avoid users setting up something incorrectly and thinking their setup is working, while the script cannot find the server when a users actually tries to connect.

This should be handled with OS independent functions/libraries.

**Comment by lubocode** [comment]
I just quickly through something together because I needed this in the Docker branch for testing.
Has to be adjusted for usage of the config file and maybe cleaned up a bit.

```
	// Check if MC server file exists at chosen location
	if mcPath[len(mcPath)-1:] != "/" {
		logger("Path without last \"/\". Adding...")
		mcPath = mcPath + "/"
	}
	mcFilePath := mcPath + mcFile
	logger("mcFilePath: " + mcFilePath)
	if _, err := os.Stat(mcFilePath); err != nil {
		if os.IsNotExist(err) {
			logger("MC server file not found.")
		}
	} else {
		logger("MC server file found.")
	}
```

**Comment by gekigek99** [comment]
added in bc373ba84a02f4ab1b85202dc47fde22ce54ea4a

**Comment by lubocode** [comment]
Changed to encompass the file and not only the folder in 05c9958
