### ISSUE TITLE
Improve logging system [logging update]

### ISSUE THREAD

**Issue by gekigek99** [gekigek99/minecraft-server-hibernation#43]
the script has come to the point where a reliable and complete log system is required.  
I don't have particular plans but a good starting point could be to add in the `logger()` function the ability to write the logs to a file.

**Comment by lubocode** [comment]
I would be for a logging system, where the logger function is extended with different logging levels and the debug flag is converted to a loggingLevel enum, which is passed as a second argument to the logger.
The enum could then entail levels like info, dev and debug, where info is used for the user, dev for development purposes and debug for intricate output like the full byte array traffic.

**Comment by gekigek99** [comment]
The various levels might be:

0. None
1. Info
2. Analytics
3. Dev
4. ByteNerd

These options should be applied to:

- Terminal
- File

Which output has which debug level would be specified in the config file

**Comment by gekigek99** [comment]
last implementation commit: 0dce714d61c210cb0a5a930797574e44274acf97

(there are other older commits related to this issue)
