### ISSUE TITLE
error management in case of error in startMinecraftServer and stopMinecraftServer

### ISSUE THREAD

**Issue by gekigek99** [gekigek99/minecraft-server-hibernation#45]
to avoid problems when issuing start and stop commands

**Comment by gekigek99** [comment]
send txt with "error: server not started" in the loading screen in case of errors

**Comment by SmirkVG** [comment]
Hi there, I'm having some issues with this program. I've tried your latest 2.0.0 release with a 1.16.4 vanilla server. I'm using the included compiled exe to run the script, and everything works fine besides one thing. I'm having an issue with the script actually issuing the server start and stop commands on my Windows 10 machine. Debug mode claims that it is successfully finding the server.jar in my server folder. The script works properly when listening for connections, and beginning the "warmup", but it doesn't actually open the server.jar. If I open the server.jar manually during this warmup, the script works for me in allowing players to join. But like the start command, if I leave the server empty, the script claims to be shutting the server down; but the server.jar continues to run. Any idea why the server.jar isn't being called/stopped when told to? Thanks.

**Comment by gekigek99** [comment]
I confirm that there is this problem...
Have you tried compiling the go program by yourself?

**Comment by SmirkVG** [comment]
When you say I need to launch the server with the startMinecraftServerWin parameter, do I need to tell the program somewhere that I’m running Windows? I checked that the serverDirPath was correct, and I also replaced the serverFileName variable with the direct path to the server.jar as you said. After doing all this I attempted running the Golang script itself through the cmd prompt, but that did not work either, so I’m not sure recompiling would change anything?

**Comment by gekigek99** [comment]
let's try seeing where the problem is step by step...

on cmd execute: `java -Xmx1024M -Xms1024M -jar "C:\\Users\\YourUserName\\Desktop\\minecraft server" nogui`

is the server launched correctly in this way?

**Comment by SmirkVG** [comment]
Yes, that works.

**Comment by gekigek99** [comment]
ok that's strange...

if you execute msh as admin does it work?
Can you share the config file you are using?

**Comment by SmirkVG** [comment]
I'm sorry, I'm an amateur when it comes to coding and I'm not sure what you mean by msh. Here's my config:

{
  "basic": {
    "serverDirPath": "D:\\Server\\java-server",
    "serverFileName": "server.jar",
    "startMinecraftServerLin": "screen -dmS minecraftServer java {-Xmx1024M -Xms1024M} -jar serverFileName nogui",
    "stopMinecraftServerLin": "screen -S minecraftServer -X stuff 'stop\\n'",
    "startMinecraftServerWin": "java {-Xmx2G -Xms1024M} -jar \"D:\\Server\\java-server\\server.jar\" nogui",
    "stopMinecraftServerWin": "stop",
    "hibernationInfo": "                   &fserver status:\n                   &b&lHIBERNATING",
    "startingInfo": "                   &fserver status:\n                    &6&lWARMING UP",
    "minecraftServerStartupTime": 20,
    "timeBeforeStoppingEmptyServer": 60,
    "checkForUpdates": true
  },
  "advanced": {
    "listenHost": "0.0.0.0",
    "listenPort": "19133",
    "targetHost": "127.0.0.1",
    "targetPort": "25565",
    "debug": false,
    "serverVersion": "1.16.4",
    "serverProtocol": "754"
  }
}

**Comment by gekigek99** [comment]
> I'm not sure what you mean by msh.

oh no don't worry it's just an abbreviation for minecraft server hibernation ahahah ;)

replace:
`"startMinecraftServerWin": "java {-Xmx2G -Xms1024M} -jar \"D:\\Server\\java-server\\server.jar\" nogui",`

with this:
`"startMinecraftServerWin": "java -Xmx2G -Xms1024M -jar serverFileName nogui",`

that should do the job ;)

**Comment by SmirkVG** [comment]
Yeah, that was how I had the config file set up before I started troubleshooting. Unfortunately not working

**Comment by gekigek99** [comment]
oh ok... can you send your initial config file (before troubleshooting)?

(have you removed the brace around `-Xmx2G -Xms1024M`?)

**Comment by SmirkVG** [comment]
No I in fact did not... Like all things, of course, the problem is always a silly one. Yes, removing the braces fixed the issue. I'm not sure why I had the intuition to remove the braces from the serverDirPath and serverFileName variables, but not the start command. Oh well. Thanks alot for your help! By the way, is there any way to have the Minecraft server console print into your console? If not that's fine -- removing the "nogui" from the config should solve that problem, albeit with a bit more messy interface.

**Comment by gekigek99** [comment]
> Like all things, of course, the problem is always a silly one.

99% of problems are silly ones ahah

> is there any way to have the Minecraft server console print into your console?

I think it is possible to do and it might be an advantage (I could avoid the usage of "screen" command for linux and users would be able to interact with the server directly from msh.

> is it possible, perhaps in a future version, for the script to tell the Minecraft server console that a player disconnected the moment they do, so that they don't have to "time out"?

sure it is... In older versions msh worked like that but i didn't like the error that was thrown on the msh console (a broken pipe error).... which doesn't impact the functionality but was not that clean... I might consider switching again to this disconnection management.

(I'll open an issue for both these questions)

**Comment by gekigek99** [comment]
(in the meantime, consider giving a star to this rep, it would be really appreciated)

**Comment by gekigek99** [comment]
> **send txt with "error: server not started" in the loading screen in case of errors**

**Comment by gekigek99** [comment]
added in: 1b087b30c2ca8c40e3139c58b9f5ae27f7308212
