### ISSUE TITLE
Add configuration for custom info (hibernation-warmup) and loading-screen messages

### ISSUE THREAD

**Issue by lubocode** [gekigek99/minecraft-server-hibernation#48]
I think it’s related, so what about adding configuration for custom hibernation and startup messages? I modified the Python version for that until now but since it’s deprecated…

Sorry if it was already present or proposed.

_Originally posted by @Br31zh in https://github.com/gekigek99/minecraft-server-hibernation/issue_comments/709141763_

**Comment by lubocode** [comment]
>I think it’s related, so what about adding configuration for custom hibernation and startup messages? I modified the Python version for that until now but since it’s deprecated…

Yes, we deprecated the Python Version simply because of too much overhead for maintenance.
We both use the Go version and as such, decided to deprecate the Python one.
However, this does not mean, that the Python version is now unusable. You can continue to use the last release and unless you run into bugs, we have not found yet, it should work fine.

As for the go version; we plan to add instructions on how to build it by yourself, but basically it is a simple matter of installing go and running the command go build minecraft-server-hibernation.go in the script folder to create yourself an executable file from the code. Modifying the code should also not be too complicated, since you successfully did so in the Python version.

https://github.com/gekigek99/minecraft-server-hibernation/issues/30#issuecomment-709204825

**Comment by gekigek99** [comment]
> basically it is a simple matter of installing go and running the command `go build minecraft-server-hibernation.go` in the script folder to create yourself an executable file from the code.

@Br31zh exacly, as a plus in next releases will include a compiled binary (no go installation stuff 😉) and I'm thinking about adding more config options in the .json file to increase configurability

**Comment by Br31zh** [comment]
Of course, it was a bad formulation, even if you hadn’t stop maintaining the Python version it’s still a good idea to permit to change that from the configuration ^^

**Comment by gekigek99** [comment]
Add configuration for custom info (hibernation-warmup) where added in a7cc6c08ad26857a746b82dd2dd1e0cd52157e8f.

configuration for custom loading-screen messages where not added since there is a %d in the string which cal lead to problems if omitted

**Comment by lubocode** [comment]
> configuration for custom loading-screen messages where not added since there is a %d in the string which cal lead to problems if omitted

@gekigek99 The string from the config could be combined with a string in the script for the countdown though?
Also, when #37 is built in, the countdown requirements might change.

**Comment by gekigek99** [comment]
Oh yes... You are right!

I will figure it out when I add this functionality (since I think it more important than a silly configurable string)
