### ISSUE TITLE
strings.ReplaceAll undefined

### ISSUE THREAD

**Issue by JoohanV** [gekigek99/minecraft-server-hibernation#50]
I just installed this, but it couldn't run. The exact message I got was
`# command-line-arguments
./minecraft-server-hibernation.go:491:21: undefined: strings.ReplaceAll`
I'm running this on an Ubuntu server install. Are there any dependencies I'm not aware of or something else of that order?

**Comment by gekigek99** [comment]
can you specify what msh version are you using?

What is the golang version? (look [here](https://github.com/Codewars/codewars.com/issues/1861#issuecomment-507417558))

**Comment by JoohanV** [comment]
It was the golang version, as you suspected. I falsely assumed the golang-go apt package would be the newest version. Problem solved.

**Comment by gekigek99** [comment]
@JoohanV if you like this project please consider giving a star!
