### ISSUE TITLE
send message in game chat

### ISSUE THREAD

**Issue by gekigek99** [gekigek99/minecraft-server-hibernation#57]
so that msh can send important messages to players when they are in-game

**Comment by gekigek99** [comment]
with the addition of minecraft terminal this should be much more easy

for now the only important message to be reported is when there is a new update

**Comment by SorrowEater** [comment]
So, you only have to listen for user input, and anything that the user types needs to be passed to the jar.
Fairly simple, but I don't know Go, so I can't help, unfortunately...

**Comment by gekigek99** [comment]
yea I was actually thinking of using this functionality for the msh to communicate to the players when they are playing... for example when there is an update for msh or msh is shutting down for whatever reason...

obviously this could then be expanded and msh could actively read the game chat so taht users can send commands to msh via game chat

**Comment by SorrowEater** [comment]
ok, so I don't know how go works, and I've never used it, but it seems simple (but possibly cumbersome). The way you send the stop command to the jar? You could either do that for every possible command (which would be stupid and not allow modded server to work at the same level), or simply pass whatever the user types to the jar, and the jar would give an error if it's not a command that would work. The /say command can be used for this specific use case, for example: `say Is everyone having fun?` would output `[Server] Is everyone having fun?` in the chat.

**Comment by gekigek99** [comment]
> I don't know how go works, and I've never used it, but it seems simple (but possibly cumbersome)

So I'm no expert (i'm not even a programmer actually... ahah) but I learned some basics in like 4-5 days while I was translating the python to golang for the first time (what a ride if I have to admit ahah...)  
I did not want to implement it in c++ because go seemed more manageable with all the connection stuff...

> The way you send the stop command to the jar?  

righ now the stop command is sent in [this way](https://github.com/gekigek99/minecraft-server-hibernation/blob/4cb52cfaa6ee23386e70df438fa2a5b0b606ae38/lib/servctrl/servctrl.go#L54)

the [execute](https://github.com/gekigek99/minecraft-server-hibernation/blob/4cb52cfaa6ee23386e70df438fa2a5b0b606ae38/lib/servctrl/cmd.go#L63) function is already used to implement the interaction between msh and the minecraft server terminal (look [here](https://github.com/gekigek99/minecraft-server-hibernation/blob/4cb52cfaa6ee23386e70df438fa2a5b0b606ae38/lib/servctrl/cmd.go#L235))

so if you want you can already interact with the minecraft server as you would normally do by writing to the msh console once the minecraft server has started...

> The /say command can be used for this specific use case, for example: `say Is everyone having fun?` would output `[Server] Is everyone having fun?` in the chat.

yes exactly... I would like to add a feature where if you have `CheckForUpdates` enebled in the config, msh will send a warning for a new update in game chat every 30 minutes or so

**Comment by SorrowEater** [comment]
Ok, so the input() module in Python would have been useful for this, but whatever the Golang equivalent is could be used in place of `Config.Commands.StopServer`. So, instead of StopServer you could have Input or something, and when the user presses enter, or newline, the input is set as Input, the execute command is passed to the jar, and msh asks for input again. It's not perfect, but it could work.

**Comment by gekigek99** [comment]
sorry... but It's not really clear what you are trying to do....

because I really don't understand what is your goal: could you do an example?

would you like to be able to stop the minecraft server within the msh application?

**Comment by gekigek99** [comment]
added in: fa54a39b963caf529f62124a537b28e09b7e8665
