### ISSUE TITLE
handleClientSocket should check client join packets based on config's ListenPort

### ISSUE THREAD

**Issue by blongty** [gekigek99/minecraft-server-hibernation#59]
Function handleClientSocket at line [267](https://github.com/gekigek99/minecraft-server-hibernation/blob/c5804b6070f6e9ec68c56aa85c471a4ccc0f1bb8/go-version/minecraft-server-hibernation.go#L267) onwards for managing client joins should be changed so it looks manages packets based on the config's ListenPort rather than looking for [221, 2].

I changed my listening port to 25565 and target port to 25555. handleClientSocket is hard-coded to look for packets [...63 **DD 2**...] which is specifically for port 25565. When changing target to port 25555 it should be looking for [...63 **D3 2**...]. What should happen is it looks for bytes based on the config's Listen port.

edit - clarification

**Comment by gekigek99** [comment]
oh ok that sounds interesting!

could you just explain how do you get that set of bytes from the number 25555? (it's kinda late now ahah ;) )

**Comment by blongty** [comment]
This would be similar to how you got 221.

**Decimal -> Hex -> Char**
25565 -> 63 **DD** -> 99 **221**
25555 -> 63 **D3** -> 99 **211**

So you have to convert the port to hex, then look for it followed by 2 for login. **You should also be looking for the full port and not just the last two hex values.**

More info on handshake packet [here](https://wiki.vg/Protocol#Handshake).

**Comment by gekigek99** [comment]
oh ok i didn't understand because you highlighted [**D3 2**] but now it's clear

WTF i never found that wiki page ahahahahaha

gonna add it to my wiki

**Comment by gekigek99** [comment]
i fixed it in 17f788e68debcc038b252940d464637a5e10891c

can you confirm?

**Comment by blongty** [comment]
It is confirmed working!
