### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by DeLaPF** [gekigek99/minecraft-server-hibernation#61]
Would it be possible to run this script on MacOS? If not how difficult of a process do you think it would be to integrate such support?

**Comment by gekigek99** [comment]
It's certainly doable... One would need to add a `runtime.GOOS == "macos"` block near the `runtime.GOOS == "windows"` (2 blocks: 1 for startup and 1 for shutdown)

I'm not an expert in macos but i think it could look similar to the windows block

right now the major issue is that i don't have any pc/vm running macos an so testing is impossible (for me)

**Comment by f8ith** [comment]
It actually works more like linux. I'm not really familar with go, but I made some simple edits to just let macOS run the same block of code as linux. 
It works great.

**Comment by gekigek99** [comment]
oh ok wow nice job then!

If you want to add the macOS block to the script you could contribute to this project!

(or just share your solution and when I have time I'll implement it myself... because I don't have a working macOS where I can test stuff :( )

> Thanks for the fantastic script!

thank you it's always nice to hear that

**Comment by f8ith** [comment]
Sure! I can submit a pull request later, I'll add a macOS config option as well based on the linux block

**Comment by gekigek99** [comment]
added in d674254cba716583ad411062b0e89cf564f8ff84

requires further testing
