### ISSUE TITLE
Server isn’t stopping

### ISSUE THREAD

**Issue by Br31zh** [gekigek99/minecraft-server-hibernation#65]
If I believe my logs, your program is launching the start command instead of stop command. If I understand correctly, it’s this part of the program:

https://github.com/gekigek99/minecraft-server-hibernation/blob/95e3603c84b3b997ff14392a1bf728d205d198d6/minecraft-server-hibernation.go#L271-L280

EDIT: I edited these lines locally, so I confirm that’s the problem

**Comment by gekigek99** [comment]
#66 was solved and merged successfully
