### ISSUE TITLE
When trying to connect it disconnects without starting the server

### ISSUE THREAD

**Issue by Bush-cat** [gekigek99/minecraft-server-hibernation#76]
2021/03/02 20:09:33 *** listening for new clients to connect...
2021/03/02 20:09:37 *** player unknown requested server info from 127.0.0.1:25555 to 127.0.0.1:25565

**Comment by gekigek99** [comment]
@Bush-cat what was the problem?

**Comment by Bush-cat** [comment]
idk why but it detected the player as unknown and didn't start the server, some time later when it detected my player name and started the server properly

**Comment by gekigek99** [comment]
Ah ok it was probably because when you refresh the servers page you are only requesting server info...  
in the request (from client to server) the player name is not specified, for the server to start (and recognize the player name) you need specifically to try to enter the minecraft server
