### ISSUE TITLE
Missing support for Paper & Purpur

### ISSUE THREAD

**Issue by BolverBlitz** [gekigek99/minecraft-server-hibernation#86]
If i use Paperclip or Purpur (Fork of Paperclip) this program gets stuck in the startup prosess. 
It would be awsome to see support for those 2 in the future.

The program also crashes (not responding to CTRL+ C) if i join the server manualy.

Tested on Windows 10 & Ubuntu 20.04 with Java 8 & 11
With MSH 2.3.0 release

**Comment by BolverBlitz** [comment]
Ok. I found version 2.3.3 in an other issue with paper as topic. 
This version works fine with both paper & purpur. Would be nice to see a final release :D

**Comment by gekigek99** [comment]
@BolverBlitz yea sorry for that...  

Right now it's a difficult period, with lots of uni exams and I really can't make a decent 2.3.3 release (might release directly version 2.4.0 in the next week or so)

If you like this project please consider giving a star... It would be very appreciated!
