### ISSUE TITLE
Console commands are not always passed to the minecraft server on pterodactyl panel

### ISSUE THREAD

**Issue by BolverBlitz** [gekigek99/minecraft-server-hibernation#90]
![grafik](https://user-images.githubusercontent.com/35345288/115054157-32f96480-9ee0-11eb-945a-16644ca81198.png)

Only one in about 20 trys will work. Version 2.3.3

**Comment by gekigek99** [comment]
Very very strange...

Are you writing "help" or " /help"?

I see a strange terminal... Are you using a sort of game manager? Or is it just a normal terminal?

What OS are you on?

**Comment by BolverBlitz** [comment]
It doesn´t matter if i write /help or help, or any other command. 

The terminal is a web terminal of the open source project pterodactyl.io.

Its a Debian docker, but i tryed Release 2.3 on my PC and it was the same problem (Windows 10 Powershell, and Ubuntu 20.04)
Also no other minecraft/gameserver has that problem in pterodactyl as far as i know.
I have written a install script for your project https://github.com/BolverBlitz/PterodactylEgg-minecraft-server-hibernation
If you wanna try, i can give you acces to a game server running that installation.

**Comment by gekigek99** [comment]
Yea I know pterodactyl... I wrote a program in golang msh-like that could be applied to every server on the panel...

Ok this is an interesting issue then...

tomorrow I'll test on my server normally (without pterodactyl) to check that I didn't mess up something with recent updates...

> I have written a install script for your project https://github.com/BolverBlitz/PterodactylEgg-minecraft-server-hibernation

nice rep!

> If you wanna try, i can give you acces to a game server running that installation.

that could be very useful... let me just check that everything is working with a normal installation  
(I think that maybe there are some problems with input interface/interaction with the ptero panel.... but in that case it's weird that every 20 tryes it works...)

**Comment by BolverBlitz** [comment]
> that could be very useful... let me just check that everything is working with a normal installation
(I think that maybe there are some problems with input interface/interaction with the ptero panel.... but in that case it's weird that every 20 tryes it works...)

I´ve tryed 2.3.3 now on my PC on Ubuntu WSL2 and the input works just fine. Strange.

**Comment by gekigek99** [comment]
> I´m very sorry for beeing annoying :(

nono don't worry about that... I'll try to think about something

If you notice something else please report it (leave the debug option set to true)

**Comment by BolverBlitz** [comment]
> If you notice something else please report it (leave the debug option set to true)

I´ll put that as default for my egg for now

**Comment by gekigek99** [comment]
It kinda difficult for me to test because on my server everything works fine...

There might be some problems in the communication between msh and pterodactyl...

It could be also something related to this... I don't know... since the minecraft server is launched on a detached child process...

https://github.com/gekigek99/minecraft-server-hibernation/blob/7bb0e3553a314028dce9f8c90fa838946c8148b2/lib/osctrl/osctrl_linux.go#L10

**Comment by BolverBlitz** [comment]
With 2.4.0 release, the commands worked great on pterodactyl. 
Both msh and mine commands. Great work!

**Comment by gekigek99** [comment]
Very well I'm happy to hear that
