### ISSUE TITLE
You can keep the server running by refreshing the MP screen

### ISSUE THREAD

**Issue by BolverBlitz** [gekigek99/minecraft-server-hibernation#91]
![grafik](https://user-images.githubusercontent.com/35345288/115054652-c337a980-9ee0-11eb-9373-e178fc2c139b.png)

Everytime i hit "Refresh" in minecraft, it gets counted as one Player joining and leaving.
Maybe implement a minimum amount of time the player needs to be connected to count as online to fix this.

Version 2.3.3

**Comment by gekigek99** [comment]
Yeah I'm aware of that...

Unfortunately it's a little difficult to implement your solution because I would need to hardcore a set amount of time as a trigger and there would be some noticeable delay and multiple possible bugs associated with that...

An better way to do it would be for the proxy package to read the first package from the client and if it's a "request server info" package then do not show the message "user joined the server" on the msh terminal

**Comment by BolverBlitz** [comment]
Ok, it was just a quick idear. I just wanted you to know about this problem.

**Comment by gekigek99** [comment]
thanks for opening the issue!  
in any case I'll keep it open to remember about this problem

also #73 might be related

**Comment by gekigek99** [comment]
It should have been solved in de690e2a6b99ed75a43970996a59cdf3a0270549

@BolverBlitz can you test version 2.3.5 to confirm?

**Comment by BolverBlitz** [comment]
![grafik](https://user-images.githubusercontent.com/35345288/115155290-8524bc00-a07f-11eb-9355-5f748a30209d.png)


With Version 2.3.5 (And same config from 2.3.3) i can´t connect to the server.
I´ve downloaded your 2.3.5 release, build with Windows to GOOS: linux & amd64

**Comment by gekigek99** [comment]
Wtf and with version 2.3.4 it works?

Could you see an error message on the minecraft client?

With debug set to true just after launching msh you should see `targeting server address: serverip:serverport` are they correct?

**Comment by BolverBlitz** [comment]
Ok, whatever happend when i wrote it, 2.3.5 works now. 
Refreshing server list won´t count as new player. Thanks

**Comment by gekigek99** [comment]
just one thing... I noticed that the new serverVersion is `Paper 1.16.5` (in your last picture)

Can you see the logo and description of the server when the server is offline? (you should see the msh logo as server logo)

**Comment by BolverBlitz** [comment]
Ok. The MSH Freeze Icon only shows up on first startup, after minecraft server was online and goes offline it just turns white.
![grafik](https://user-images.githubusercontent.com/35345288/115161340-70efb780-a09d-11eb-8b9a-040cbdd7ca20.png)

When server in online, i see serverversion of the server + MOTD or the server.
When server goes offline, picture is just white (as in picture) and the MOTD is hibernating (as in picture).

> (because when I wrote it I expected serverVersion to be just 1.16.5 and seems impossible that it works just like that.... :)

My Egg writes custom name there on first instll. (EBG.PW 1.16.5) for a 1.16.5 Server ofc
After i join minecraft, the config chances to Paper 1.16.5 (or Purpur, depends what i use ofc) and that stays then forever.

**Comment by gekigek99** [comment]
ok let's open an issue for that... this issue was closed
