### ISSUE TITLE
Minecraft Server stays on without users online & MSH Commands

### ISSUE THREAD

**Issue by BolverBlitz** [gekigek99/minecraft-server-hibernation#95]
A user tolled me that his server stayed online with 0 players (Also 0 players refreshing #91 & #73)
He could join and leave the server, seen in the screenshot below. 
The Stop time was 60s but last player activity happend ~11:05 and current time is 11:08 so server should be stopped.

![grafik](https://user-images.githubusercontent.com/35345288/115109446-0d1e9f00-9f76-11eb-9f78-38ceb1812c55.png)

A better logging would be needed to look in those cases where the server doesn't stop #43 

MSH-Commands: Having commands to stop the minecraft server like "msh stop" that will run the stop line in the config or "msh start" to start it (Nice if you add plugins)

For Pterodactyl a better way than ^C would be nice to have. Like "msh exit", that will stop minecraft and then kill the msh prosess.

**Comment by BolverBlitz** [comment]
![grafik](https://user-images.githubusercontent.com/35345288/115112411-bb7e1080-9f85-11eb-9f8c-32d6376a4562.png)
Also happend on my PC localy now :(

**Comment by gekigek99** [comment]
> MSH-Commands: Having commands to stop the minecraft server like "msh stop" that will run the stop line in the config or "msh start" to start it

you mean some commands to send to msh to manually start the server?

> (Nice if you add plugins)

what do you mean?

> For Pterodactyl a better way than ^C would be nice to have. Like "msh exit", that will stop minecraft and then kill the msh prosess.

yea i know, I am planning to add msh commands

**Comment by gekigek99** [comment]
> Also happend on my PC localy now :(

Is it possible that the client remains in the servers page and every few seconds it sends a "request server info" packet that is interpreted by msh as a player joining and leaving?

**Comment by BolverBlitz** [comment]
No, that wasn´t the case on my PC. I closed Miencraft and there is no IP route for other PCs to see my server running in WSL.

**Comment by gekigek99** [comment]
it this problem occurring always or only some times?

For me there is are no problems... can you test it outside the WSL?

With debug set to true, after 60 seconds (or what you have set) do you see the highlighted line?

![image](https://user-images.githubusercontent.com/53654579/115159919-e6f02080-a095-11eb-9674-8e179dfca2df.png)

**Comment by BolverBlitz** [comment]
I´ve now upgraded all servers to 2.3.5 and that never happend again. 

A new problem came up from a user, and i can replicate it 100%. 

A 1.16.5 server works great for my users so far, but running 1.12.2 server, MSH will kill the server after the set time in config, the player count doesn´t matter.
Here example log by a user: https://pastie.io/cafnjq.vbs

(I made sure, that servers are clean installs and no up/downgrade)

**Comment by gekigek99** [comment]
@BolverBlitz I opened a new issue for that: #98
