### ISSUE TITLE
Force close server when stop dosn´t work

### ISSUE THREAD

**Issue by BolverBlitz** [gekigek99/minecraft-server-hibernation#99]
A user installed a plugin on his server that remaps commands, so the stop command won´t work to stop it.
Solution: Kill server wit ^C after 2x the time in the config. (I know, server wont save chunks)

**Comment by gekigek99** [comment]
So you mean something like this behaviour:
1. Msh sends stop command
2. Server does not close within 10 seconds
3. Msh sends  ^C to server

**Comment by BolverBlitz** [comment]
Yes, but i mean it should wait another TimeBeforeStoppingEmptyServer just to be sure it dosn´t kill it on exident.

Adding that to config, well its nice but a user could chance that ^^

I think it would be best to build that into msh without config, the server could just freeze on stop anaways.

**Comment by gekigek99** [comment]
added here: 3a6b0dfd83d0080c2aa590cd851a9f755fa04b97

_(please notice there is a bugfix after version 2.4.1)_


to override the config just add at line 79:
`Config.Commands.StopServerAllowKill = 10`

https://github.com/gekigek99/minecraft-server-hibernation/blob/c2770ac827718a59fe955314c4a9ba4b80a65d36/lib/confctrl/confctrl.go#L73-L80

**Comment by gekigek99** [comment]
@BolverBlitz is it working as expected? (So I can close the issue)

**Comment by BolverBlitz** [comment]
Had not time to test it because i´m working on something for myself

**Comment by gekigek99** [comment]
Okok no problem! Keep me updated about this testing ;)

**Comment by gekigek99** [comment]
i tested it and it appears to be working as expected
